<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="87" started-at="2018-08-09T20:29:44Z" finished-at="2018-08-09T20:29:44Z">
    <groups>
      <group name="smoke">
        <method signature="ExceptionTimeOutTestDemo.test1()[pri:0, instance:com.testngtests.ExceptionTimeOutTestDemo@458c1321]" name="test1" class="com.testngtests.ExceptionTimeOutTestDemo"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Default test" duration-ms="87" started-at="2018-08-09T20:29:44Z" finished-at="2018-08-09T20:29:44Z">
      <class name="com.testngtests.ExceptionTimeOutTestDemo">
        <test-method status="FAIL" signature="test1()[pri:0, instance:com.testngtests.ExceptionTimeOutTestDemo@458c1321]" name="test1" duration-ms="40" started-at="2018-08-09T20:29:44Z" finished-at="2018-08-09T20:29:44Z">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method com.testngtests.ExceptionTimeOutTestDemo.test1() didn't finish within the time-out 2]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testngtests.ExceptionTimeOutTestDemo.test1() didn't finish within the time-out 2
at java.io.BufferedWriter.write(BufferedWriter.java:220)
at java.io.Writer.write(Writer.java:157)
at java.io.BufferedWriter.newLine(BufferedWriter.java:243)
at java.io.PrintStream.newLine(PrintStream.java:544)
at java.io.PrintStream.println(PrintStream.java:737)
at com.testngtests.ExceptionTimeOutTestDemo.test1(ExceptionTimeOutTestDemo.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- com.testngtests.ExceptionTimeOutTestDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
